[package]
name = "ld_emit_build"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1"
ureq = "3"
quote = "1"
proc-macro2 = "1"
syn = { version = "2", features = ["full", "parsing"] }
prettyplease = "0.2"
